version: 2.1
jobs:
  build_and_test:
    docker:
      - image: cimg/go:1.16
        auth: 
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/calculator
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: " check the test"
          command: |
            cd package
            go test

workflows:
  build_and_test:
    jobs:
      - build_and_test